apiVersion: apps/v1

kind: Deployment

metadata:
  name: sre-ops-site-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: sre-ops-site

  template:
    metadata:
      labels:
        app: sre-ops-site

    spec:
      containers:
        - name: sre-ops-site

          image: sre-ops-static-site:latest

          envFrom:
            - configMapRef:
                name: sre-ops-site-config

          ports:
            - containerPort: 80

          readinessProbe:
            httpGet:
              path: /
              port: 80

            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80

            initialDelaySeconds: 15
            periodSeconds: 20
